version: '3.1'

services:
  db:
    image: 'postgres:14.1'
    restart: unless-stopped
    volumes:
      - ./volumes/postgresql/data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DB: nest
    ports:
      - 5432:5432
    networks:
      - postgres

networks:
  postgres:
    driver: bridge
